export const CATEGORIES_ACTION_TYPE = {
  FETCH_CATEGORIES_START: "categories/SET_CATEGORIES",
  FETCH_CATEGORIES_SUCCESS: "categories/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "categories/SET_CATEGORIES_FAILED",
};